upstream app {
    server app:3333;
}

limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/s;
server {
    listen 90;
    server_name localhost;

    location / {
	limit_req zone=mylimit burst=10 nodelay;
	limit_req_status 429;        
	proxy_pass http://app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
